name: SonarQube Scan

on:
  workflow_call:
    inputs:
      run_sonar:
        description: Run SonarQube scan
        required: false
        default: true
        type: boolean
    secrets:
      SONARQUBE_TOKEN:
        required: false

jobs:
  sonar:
    runs-on: ubuntu-latest
    if: inputs.run_sonar
    permissions:
      contents: read
    env:
      SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: SonarQube scan
        if: env.SONARQUBE_TOKEN != ''
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ env.SONARQUBE_TOKEN }}
